/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitcamp.lms;

public class App {
   public static void main(String[] args) {
java.util.Scanner kb = new java.util.Scanner(System.in);

 int[] no = new int [100];
 int[] total = new int [100];
 int[] dlftlrks = new int[100];
 String[] start = new String[100];
 String[] end = new String[100];
 String[] sodyd = new String[100];
 String[] title = new String[100];
 int a = 0 ;
 String b  = " " ;
 int c = 0 ;
 okok:
 while (true) {
   System.out.print("번호? ");
   no[a] =  kb.nextInt();
   kb.nextLine();
   
   System.out.print("수업명? ");
   title[a] =kb.nextLine();
   
   System.out.print("수업내용? ");
   sodyd[a] =kb.nextLine();
   
   System.out.print("시작일? ");
   start[a] =kb.nextLine();
   
   System.out.print("종료일? ");
   end[a] =kb.nextLine();
   
   System.out.print("총수업시간? ");
   total[a] =  kb.nextInt();
   kb.nextLine();
   
   System.out.print("일수업시간? ");
   dlftlrks[a] =  kb.nextInt();
   kb.nextLine();
   System.out.print("계속 입력하시겠습니까?(Y/n)");
   
   b = kb.next();
   
   if(b.equals("n")){
     while (c <= a) {
       System.out.printf("%d, %s , %s ~ %s, %d\n",no[c],title[c],start[c],end[c],total[c] );
       c++;
           if( c > a) {
             kb.close();
             break okok;
           }
     }
   }
  
   a++;
 
 
 
     }
   }

}