/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitcamp.lms;

public class App {
   public static void main(String[] args) {
 java.util.Scanner kb  = new java.util.Scanner(System.in);
     
     System.out.printf("번호? ");
     int n = kb.nextInt();
     kb.nextLine();
    
     System.out.printf("수업명? ");
     String sb = kb.nextLine();
     
     System.out.printf("수업내용? ");
     String sb1 = kb.nextLine();
     
     
     System.out.printf("시작일? ");
     String start = kb.nextLine();
    
     
     System.out.printf("종료일? ");
     String end = kb.nextLine();

     
     System.out.printf("총수업시간? ");
     int at = kb.nextInt();
     kb.nextLine();
     
     System.out.printf("일수업시간? ");
     int dt = kb.nextInt();
     kb.nextLine();
     
    System.out.printf(" 번호: %d\n 수업명: %s\n 수업내용: %s\n 기간: %s ~ %s\n 총수업시간: %d\n 일수업시간: %d\n",n,sb,sb1,start,end,at,dt);
    /* System.out.printf("번호: %d\n", n);
     System.out.printf("수업명: %s\n", sb);
     System.out.printf("수업내용: %s\n", sb1);
     System.out.printf("시작일: %s\n", start);
     System.out.printf("종료일: %s\n", end);
     System.out.printf("총수업시간: %s 시간\n",at);
     System.out.printf("일수업시간: %s 시간\n",dt);
     */
     
   }
}
