/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitcamp.lms;

public class App2 {
   public static void main(String[] args) {
     java.util.Scanner kb = new java.util.Scanner(System.in);
     java.util.Date date = new java.util.Date();
     java.util.Date today = new java.util.Date();
     int[]no = new int[100];
     int[]ho = new int[100];
     String[]name = new String[100];
     String[]add = new String[100];
     String[]pic = new String[100];
     String[]bun = new String[100];
     String d = " ";
     int inde = 0 ;
 
  while(true) {
    
      System.out.print("번호? ");
      no[inde]= kb.nextInt();
      kb.nextLine();
    
      System.out.print("이름? ");
      name[inde]= kb.next();
   
      System.out.print("이메일? ");
      add[inde]= kb.next();
     
      System.out.print("암호? ");
      ho[inde]= kb.nextInt();
      kb.nextLine();
    
      System.out.print("사진? ");
      pic[inde]= kb.next();
     
      System.out.print("전화? ");
      bun[inde]= kb.next();
      
      System.out.print("계속 입력하시겠습니까? (y/n)");
      d = kb.next();
      
      if (!d.equals("Y") &&!d.equals("y") ) {
        for(int i =0 ; i<=inde; i++) {
        System.out.printf("%d, %s, %s, %s, 2019-01-01",no[i],name[i],add[i],bun[i]);
        }    
         kb.close(); 
        break ;
      }
      inde++;
    }
   }
}
