/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitcamp.lms;

public class App3 {
   public static void main(String[] args) {
     java.util.Scanner kb = new java.util.Scanner(System.in);
     
     int []no = new int[100];
     String[]text = new String[100];
     int inde = 0;
     
     String date = "2019-01-01";
     String a = "0";
     int i = 0;
     
     while(true) {
     
     System.out.print("번호? ");
     no[inde] = kb.nextInt();
     kb.nextLine();
     
     System.out.print("내용? ");
     text[inde] = kb.nextLine();
     
     System.out.print("계속 입력하시겠습니가?(y/n) ");
     String d = kb.next();
     
     if (!d.equalsIgnoreCase("y")){
         while(i<=inde) {
           System.out.printf("%d, %s,%s,%s\n",no[i],text[i],date,a);
             i++;
         }
         break;
     }
     inde++;
     
     }
     
     
       
   }
}
