/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitcamp.lms;

public class App2 {
   public static void main(String[] args) {
     java.util.Scanner kb  = new java.util.Scanner(System.in);
     java.util.Date today = new java.util.Date();
     
     System.out.print("번호? ");
     int n = kb.nextInt();
     kb.nextLine();
     
     System.out.print("이름? ");
     String name = kb.next();
     
     System.out.print("이메일? ");
     String mail = kb.next();
     
     System.out.print("암호? ");
     int b = kb.nextInt();
     kb.nextLine();
     
     
     System.out.print("사진?");
     String pt = kb.next();
     
     System.out.print("전화?");
     String ph = kb.next();
     
     System.out.printf(" 번호:%d\n 이름:%s\n 이메일:%s\n 암호:%d\n "
         + "사진:%s\n 전화:%s \n", n,name,mail,b,pt,ph);
     System.out.printf("가입일: %1$tY-%1$tm-%1$td\n", today);
     
     
     
     
   }
}
